name: NoParticles
main: com.dsnyder.noparticles.NoParticles
version: 1.1.1
author: Dan Snyder
description: A simple plugin that stops particle effects associated with potions
commands:
  noparticles:
    description: Main command for NoParticles
    usage: /noparticles [subcommand] ...